// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SDKCommand.proto

package com.sinkinchan.nativesocketdemo.proto;

public final class SDKCommandProto {
  private SDKCommandProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SDKCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sdk.SDKCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 value = 10;</code>
     */
    int getValue();

    /**
     * <code>.sdk.SDKCommand.CommandType commandType = 1;</code>
     */
    int getCommandTypeValue();
    /**
     * <code>.sdk.SDKCommand.CommandType commandType = 1;</code>
     */
    com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType getCommandType();
  }
  /**
   * Protobuf type {@code sdk.SDKCommand}
   */
  public  static final class SDKCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sdk.SDKCommand)
      SDKCommandOrBuilder {
    // Use SDKCommand.newBuilder() to construct.
    private SDKCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SDKCommand() {
      value_ = 0;
      commandType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SDKCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              commandType_ = rawValue;
              break;
            }
            case 80: {

              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.internal_static_sdk_SDKCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.internal_static_sdk_SDKCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.class, com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.Builder.class);
    }

    /**
     * Protobuf enum {@code sdk.SDKCommand.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *连接成功
       * </pre>
       *
       * <code>CONNECT_SUCCESS = 0;</code>
       */
      CONNECT_SUCCESS(0),
      /**
       * <code>TEST_MESSAGE_RESULT = 1;</code>
       */
      TEST_MESSAGE_RESULT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *连接成功
       * </pre>
       *
       * <code>CONNECT_SUCCESS = 0;</code>
       */
      public static final int CONNECT_SUCCESS_VALUE = 0;
      /**
       * <code>TEST_MESSAGE_RESULT = 1;</code>
       */
      public static final int TEST_MESSAGE_RESULT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CommandType valueOf(int value) {
        return forNumber(value);
      }

      public static CommandType forNumber(int value) {
        switch (value) {
          case 0: return CONNECT_SUCCESS;
          case 1: return TEST_MESSAGE_RESULT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CommandType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CommandType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sdk.SDKCommand.CommandType)
    }

    /**
     * Protobuf enum {@code sdk.SDKCommand.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0),
      /**
       * <code>FAILED = 1;</code>
       */
      FAILED(1),
      /**
       * <code>LOADING = 2;</code>
       */
      LOADING(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAILED = 1;</code>
       */
      public static final int FAILED_VALUE = 1;
      /**
       * <code>LOADING = 2;</code>
       */
      public static final int LOADING_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAILED;
          case 2: return LOADING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.getDescriptor().getEnumTypes().get(1);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sdk.SDKCommand.Status)
    }

    public static final int VALUE_FIELD_NUMBER = 10;
    private int value_;
    /**
     * <code>int32 value = 10;</code>
     */
    public int getValue() {
      return value_;
    }

    public static final int COMMANDTYPE_FIELD_NUMBER = 1;
    private int commandType_;
    /**
     * <code>.sdk.SDKCommand.CommandType commandType = 1;</code>
     */
    public int getCommandTypeValue() {
      return commandType_;
    }
    /**
     * <code>.sdk.SDKCommand.CommandType commandType = 1;</code>
     */
    public com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType getCommandType() {
      com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType result = com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType.valueOf(commandType_);
      return result == null ? com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commandType_ != com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType.CONNECT_SUCCESS.getNumber()) {
        output.writeEnum(1, commandType_);
      }
      if (value_ != 0) {
        output.writeInt32(10, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandType_ != com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType.CONNECT_SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, commandType_);
      }
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand)) {
        return super.equals(obj);
      }
      com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand other = (com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand) obj;

      boolean result = true;
      result = result && (getValue()
          == other.getValue());
      result = result && commandType_ == other.commandType_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      hash = (37 * hash) + COMMANDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + commandType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sdk.SDKCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sdk.SDKCommand)
        com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.internal_static_sdk_SDKCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.internal_static_sdk_SDKCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.class, com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.Builder.class);
      }

      // Construct using com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = 0;

        commandType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.internal_static_sdk_SDKCommand_descriptor;
      }

      public com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand getDefaultInstanceForType() {
        return com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.getDefaultInstance();
      }

      public com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand build() {
        com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand buildPartial() {
        com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand result = new com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand(this);
        result.value_ = value_;
        result.commandType_ = commandType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand) {
          return mergeFrom((com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand other) {
        if (other == com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.getDefaultInstance()) return this;
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        if (other.commandType_ != 0) {
          setCommandTypeValue(other.getCommandTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int value_ ;
      /**
       * <code>int32 value = 10;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>int32 value = 10;</code>
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 value = 10;</code>
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }

      private int commandType_ = 0;
      /**
       * <code>.sdk.SDKCommand.CommandType commandType = 1;</code>
       */
      public int getCommandTypeValue() {
        return commandType_;
      }
      /**
       * <code>.sdk.SDKCommand.CommandType commandType = 1;</code>
       */
      public Builder setCommandTypeValue(int value) {
        commandType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.sdk.SDKCommand.CommandType commandType = 1;</code>
       */
      public com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType getCommandType() {
        com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType result = com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType.valueOf(commandType_);
        return result == null ? com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.sdk.SDKCommand.CommandType commandType = 1;</code>
       */
      public Builder setCommandType(com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        commandType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.sdk.SDKCommand.CommandType commandType = 1;</code>
       */
      public Builder clearCommandType() {
        
        commandType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sdk.SDKCommand)
    }

    // @@protoc_insertion_point(class_scope:sdk.SDKCommand)
    private static final com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand();
    }

    public static com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SDKCommand>
        PARSER = new com.google.protobuf.AbstractParser<SDKCommand>() {
      public SDKCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SDKCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SDKCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SDKCommand> getParserForType() {
      return PARSER;
    }

    public com.sinkinchan.nativesocketdemo.proto.SDKCommandProto.SDKCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdk_SDKCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdk_SDKCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020SDKCommand.proto\022\003sdk\"\272\001\n\nSDKCommand\022\r" +
      "\n\005value\030\n \001(\005\0220\n\013commandType\030\001 \001(\0162\033.sdk" +
      ".SDKCommand.CommandType\";\n\013CommandType\022\023" +
      "\n\017CONNECT_SUCCESS\020\000\022\027\n\023TEST_MESSAGE_RESU" +
      "LT\020\001\".\n\006Status\022\013\n\007SUCCESS\020\000\022\n\n\006FAILED\020\001\022" +
      "\013\n\007LOADING\020\002B8\n%com.sinkinchan.nativesoc" +
      "ketdemo.protoB\017SDKCommandProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sdk_SDKCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sdk_SDKCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdk_SDKCommand_descriptor,
        new java.lang.String[] { "Value", "CommandType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
